# Generated by Django 4.2.5 on 2023-09-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date_pqrs', models.DateField(verbose_name='Fecha solicitud PQRS')),
                ('response_dates', models.CharField(max_length=100, verbose_name='Metodo de respuesta PQRS')),
                ('type_pqrs', models.FloatField(verbose_name='Tipo PQRS')),
                ('state', models.FloatField(verbose_name='estado PQRS')),
                ('priority', models.FloatField(verbose_name='Prioridad')),
            ],
            options={
                'verbose_name': 'Atencion cliente',
                'verbose_name_plural': 'Atencion Clientes',
                'db_table': 'Atencion cliente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Cita')),
                ('quote_value', models.DateField(verbose_name='Valor cita')),
                ('virtual_onsite', models.FloatField(verbose_name='Virtual o presencial')),
                ('appointment_status', models.FloatField(verbose_name='Estado de cita')),
                ('location', models.FloatField(verbose_name='Ubicacion')),
                ('appointment_type', models.FloatField(verbose_name='Tipo de cita')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'Cita',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sale', models.DateField(verbose_name='Fecha de venta')),
                ('payment_method', models.CharField(max_length=100, verbose_name='Metodo de pago')),
                ('coupons_available', models.FloatField(verbose_name='Cupones disponibles')),
                ('receipt_number', models.FloatField(verbose_name='Numero de recibo')),
                ('unit_value', models.FloatField(verbose_name='Valor unitario')),
                ('total_value', models.FloatField(verbose_name='Valor total')),
                ('quantity', models.FloatField(verbose_name='Cantidad')),
                ('order_number', models.FloatField(verbose_name='Numero de orden')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'Venta',
                'ordering': ['id'],
            },
        ),
    ]
