# Generated by Django 4.2.4 on 2023-09-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_service_rendezvous_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_service',
            name='priority',
            field=models.CharField(max_length=100, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='customer_service',
            name='state',
            field=models.CharField(max_length=100, verbose_name='estado PQRS'),
        ),
        migrations.AlterField(
            model_name='customer_service',
            name='type_pqrs',
            field=models.CharField(max_length=100, verbose_name='Tipo PQRS'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='appointment_status',
            field=models.CharField(max_length=100, verbose_name='Estado de cita'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='appointment_type',
            field=models.CharField(max_length=100, verbose_name='Tipo de cita'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='quote_value',
            field=models.FloatField(verbose_name='Valor cita'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='virtual_onsite',
            field=models.CharField(max_length=100, verbose_name='Virtual o presencial'),
        ),
    ]
